#include "stdafx.h"
#include "CppUnitTest.h"

#include "Base64.h"
#include "Md5.h"


using namespace Microsoft::VisualStudio::CppUnitTestFramework;
using namespace Base64;
using namespace Md5;


namespace Encodings_test
{

	TEST_CLASS(Encodings_tests)
	{
	public:
		
		TEST_METHOD(TestBase64)
		{
			std::string str1 = "Power overwhelming";		// length is 18 (18 % 3 == 0)
			std::string res1 = "UG93ZXIgb3ZlcndoZWxtaW5n";	// Generated by the independent base64 encoder

			std::string str2 = "Hello, world!";				// length is 13 (13 % 3 == 1)
			std::string res2 = "SGVsbG8sIHdvcmxkIQ==";		// Generated by the independent base64 encoder

			std::string str3 = "Show me the money";			// length is 17 (17 % 3 == 2)
			std::string res3 = "U2hvdyBtZSB0aGUgbW9uZXk=";	// Generated by the independent base64 encoder

			std::string tmp;
			
			tmp = Base64_Encode(str1);
			Assert::IsTrue(tmp.compare(res1) == 0, L"Base64 encoding error.");
			tmp = Base64_Decode(tmp);
			Assert::IsTrue(str1.compare(tmp) == 0, L"Base64 decoding error.");

			tmp = Base64_Encode(str2);
			Assert::IsTrue(tmp.compare(res2) == 0, L"Base64 encoding error.");
			tmp = Base64_Decode(tmp);
			Assert::IsTrue(str2.compare(tmp) == 0, L"Base64 decoding error.");

			tmp = Base64_Encode(str3);
			Assert::IsTrue(tmp.compare(res3) == 0, L"Base64 encoding error.");
			tmp = Base64_Decode(tmp);
			Assert::IsTrue(str3.compare(tmp) == 0, L"Base64 decoding error.");

			Logger::WriteMessage("Base64 encoding and decoding are OK.");
		}

		TEST_METHOD(TestMd5)
		{
			// 512 % str1.size() < 448
			std::string str1 = "md5";
			std::string res1 = "1BC29B36F623BA82AAF6724FD3B16718";

			// 512 % str2.size() > 448
			std::string str2 =
				"The quick brown fox jumps over the lazy dog and The quick brown fox jumps over the lazy dog,"
				"The quick brown fox jumps over the lazy dog and The quick brown fox jumps over the lazy dog,"
				"The quick brown fox jumps over the lazy dog and The quick brown fox jumps over the lazy dog,"
				"The quick brown fox jumps over the lazy dog and The quick brown fox jumps over the lazy dog,"
				"The quick brown fox jumps over the lazy dog and The quick brown fox jumps over the lazy dog,";
			std::string res2 = "C93D3BF7A7C4AFE94B64E30C2CE39F4F";

			// Empty string test
			std::string str3 = "";
			std::string res3 = "D41D8CD98F00B204E9800998ECF8427E";

			std::vector<int8_t> tmp;

			tmp = Md5_Encode(std::vector<uint8_t>(str1.begin(), str1.end()));
			char buf[33];
			for (int i = 0; i<16; i++)
				sprintf(buf + i * 2, "%02x", tmp[i]);
			buf[32] = 0;
			std::string str(buf);

			tmp = Md5_Encode(std::vector<uint8_t>(str2.begin(), str2.end()));
			tmp = Md5_Encode(std::vector<uint8_t>(str3.begin(), str3.end()));

			Logger::WriteMessage("Md5 encoding is OK.");
		}

	};

}
